# -*- coding: utf-8 -*-
"""pinn_electricity_load_forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mB8IgjGjhDVd_Je8TmXx9urQTQnOeqUv
"""

# =========================
# 1. IMPORTS
# =========================
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
import zipfile

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# =========================
# 2. DOWNLOAD DATASET
# =========================
!wget -O power.zip https://archive.ics.uci.edu/static/public/235/individual+household+electric+power+consumption.zip

with zipfile.ZipFile('power.zip', 'r') as zip_ref:
    zip_ref.extractall()

df = pd.read_csv("household_power_consumption.txt", sep=';', low_memory=False)

# =========================
# 3. CLEAN DATA
# =========================
df = df.replace('?', np.nan).dropna()

for col in df.columns[2:]:
    df[col] = pd.to_numeric(df[col])

df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'])
df = df.sort_values('Datetime')

df = df.iloc[:30000]  # smaller for speed

# =========================
# 4. FEATURES
# =========================
features = ['Voltage', 'Global_intensity']
target = 'Global_active_power'

X = df[features].values
y = df[target].values.reshape(-1,1)
t = np.arange(len(df)).reshape(-1,1)

# =========================
# 5. NORMALIZE
# =========================
scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()

X = scaler_X.fit_transform(X)
y = scaler_y.fit_transform(y)
t = t / t.max()

# =========================
# 6. SPLIT
# =========================
split = int(0.8 * len(X))

X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]
t_train, t_test = t[:split], t[split:]

# =========================
# 7. TENSORS
# =========================
def to_tensor(x, grad=False):
    return torch.tensor(x, dtype=torch.float32, requires_grad=grad).to(device)

X_train = to_tensor(X_train)
y_train = to_tensor(y_train)
t_train = to_tensor(t_train, grad=True)

X_test = to_tensor(X_test)
y_test = to_tensor(y_test)
t_test = to_tensor(t_test, grad=True)

# =========================
# 8. MODEL
# =========================
class PINN(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(3, 64),
            nn.Tanh(),
            nn.Linear(64, 64),
            nn.Tanh(),
            nn.Linear(64, 1)
        )

    def forward(self, X, t):
        return self.net(torch.cat([X, t], dim=1))

model = PINN().to(device)

# =========================
# 9. PHYSICS LOSS
# =========================
def physics_loss(model, X, t):
    pred = model(X, t)

    dP_dt = torch.autograd.grad(pred, t,
                                grad_outputs=torch.ones_like(pred),
                                create_graph=True)[0]

    loss_smooth = torch.mean(dP_dt**2)

    V = X[:,0:1]
    I = X[:,1:2]
    P_physics = V * I

    loss_physics = torch.mean((pred - P_physics)**2)

    loss_stability = torch.mean((pred[1:] - pred[:-1])**2)

    return loss_smooth + loss_physics + 0.1 * loss_stability

# =========================
# 10. TRAIN
# =========================
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

for epoch in range(2000):
    optimizer.zero_grad()

    pred = model(X_train, t_train)

    loss_data = torch.mean((pred - y_train)**2)
    loss_phys = physics_loss(model, X_train, t_train)

    loss = loss_data + 0.3 * loss_phys

    loss.backward()
    optimizer.step()

    if epoch % 200 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.6f}")

# =========================
# 11. EVALUATE
# =========================
model.eval()

pred_test = model(X_test, t_test).detach().cpu().numpy()
y_test_np = y_test.detach().cpu().numpy()

pred_test = scaler_y.inverse_transform(pred_test)
y_test_np = scaler_y.inverse_transform(y_test_np)

# =========================
# 12. METRICS
# =========================
rmse = np.sqrt(mean_squared_error(y_test_np, pred_test))
mae = mean_absolute_error(y_test_np, pred_test)

print(f"RMSE: {rmse:.4f}")
print(f"MAE: {mae:.4f}")

# =========================
# 13. PLOT
# =========================
plt.figure(figsize=(10,5))
plt.plot(y_test_np[:300], label='Actual')
plt.plot(pred_test[:300], label='Predicted')
plt.legend()
plt.title("PINN Electricity Forecast")
plt.show()











